version: '2'

networks: 
  supplychain:

services: 

  ca_thayson:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.thayson.supplychain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports: 
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/thayson:/etc/hyperledger/fabric-ca-server
    container_name: ca.thayson.supplychain.com
    hostname: ca.thayson.supplychain.com
    networks: 
      - supplychain

  ca_cohuong:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.cohuong.supplychain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports: 
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/cohuong:/etc/hyperledger/fabric-ca-server
    container_name: ca.cohuong.supplychain.com
    hostname: ca.cohuong.supplychain.com
    networks: 
      - supplychain

  ca_orderer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports: 
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks: 
      - supplychain